### ISSUE TITLE
Grocer

### ISSUE THREAD

**Issue by DeanBentley** [rocwang/grocer-issues#60] opened 2022-07-12 09:29 UTC
I can't beleive I have to go through all this, signing up to another site to report a fault with the GROCER app.... And this site makes no sense to me at all... I have been on the GROCER app for a couple of months now...great app but unfortunatley is has stopped working....no products show up using the scanner or when you manually search the item shows up but once you click on it it does take me to any store.  I have ununstalled the app and installed.... have I just wasted my time with my complaint?...as a feel this won't be taken seriously.... 
Regards. 
Dean
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rocwang** [comment] 2022-07-13 07:18
It looks like no store is selected or the selected stores are reset in your case. Maybe double check if you have any store selected in the "stores" tab?

I'm sorry for your frustrating experience. It could be very confusing if indeed it was caused by no store selected. It should be fixed by https://github.com/rocwang/grocer-issues/issues/18

**Comment by DeanBentley** [comment] 2022-07-13 08:24
OK....I take everything back...my apologies...and thanks for your quick
response. I pretty much use this awesome app daily so am unsure why my
selected stores disappeared.  I will check for the obvious next time.

Kind regards

**Closed** 2022-07-13 21:03 UTC

**Comment by rocwang** [comment] 2022-07-14 07:05
Hi @DeanBentley,

Yes, I'm aware that sometimes the selected store might be reset. As Grocer is built upon web browser technologies, when the browsing history / cached web pages are cleared by the browser, the selected stored might be deleted as well.

In the future, Grocer would support storing such account data "in the cloud", which would resolve such problem.
